- name: Install epel-release
  yum: 
    name: ['epel-release']
    state: installed

- name: Install darkhttpd
  yum: 
    name: ['darkhttpd']
    state: installed

- name: Create /var/www directory
  file:
    path: /var/www
    state: directory
    mode: '0755'

- name: Enable and start darkhttpd
  systemd:
    enabled: yes
    state: started
    daemon_reload: yes
    name: darkhttpd

- name: Update darkhttpd config
  copy: 
    src: darkhttpd
    dest: /etc/sysconfig/darkhttpd
    mode: 0644
  register: conf

- name: Restart darkhttpd on config change
  systemd:
    state: restarted
    name: darkhttpd
  when: conf.changed == true
